export const UPDATE_PETS = "UPDATE_PETS";

export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";
export const TOGGLE_FAVORITES = "TOGGLE_FAVORITES";

export const UPDATE_USER = "UPDATE_USER";